### ISSUE TITLE
BLEU score

### ISSUE THREAD

**Issue by wangqi1996** [wszlong/sb-nmt#4]
Which block of your code calculates the BLEU score

**Comment by wszlong** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    我是翻译出来之后，再计算BLEU值的。所以这块不在代码里，附件是BLEU测试的脚本，供参考。周龙
    
    
     
    
 

    On 9/12/2019 11:05，wangqi1996<notifications@github.com> wrote： 


请问您的代码的哪块是计算BLEU得分的呀

**Comment by wangqi1996** [comment]
thanks

**Comment by wangqi1996** [comment]
您好，没有收到附件，能帮忙再发一遍嘛？
感谢


------------------
祝好！王东琪


 




------------------ 原始邮件 ------------------
发件人: "Long Zhou"<notifications@github.com>;
发送时间: 2019年9月12日(星期四) 下午2:44
收件人: "wszlong/sb-nmt"<sb-nmt@noreply.github.com>;
抄送: "王东琪"<1528272574@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [wszlong/sb-nmt] BLEU score (#4)



 
 
      
 
 
 
     font{ 
         line-height: 1.6; 
     } 
     ul,ol{ 
         padding-left: 20px; 
         list-style-position: inside; 
     } 
 
 
     
     
         
             
         
     我是翻译出来之后，再计算BLEU值的。所以这块不在代码里，附件是BLEU测试的脚本，供参考。周龙
     
     
      
     
  
 
     On 9/12/2019 11:05，wangqi1996<notifications@github.com> wrote： 
 
 
 请问您的代码的哪块是计算BLEU得分的呀

**Comment by wszlong** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    
        
            
        
    请查收~
    
        
        

        
    

    On 9/16/2019 21:07，wangqi1996<notifications@github.com> wrote： 


您好，没有收到附件，能帮忙再发一遍嘛？



感谢











------------------



祝好！王东琪











 



















------------------ 原始邮件 ------------------



发件人: "Long Zhou"<notifications@github.com>;



发送时间: 2019年9月12日(星期四) 下午2:44



收件人: "wszlong/sb-nmt"<sb-nmt@noreply.github.com>;



抄送: "王东琪"<1528272574@qq.com>;"Author"<author@noreply.github.com>;



主题: Re: [wszlong/sb-nmt] BLEU score (#4)















 



 



      



 



 



 



     font{ 



         line-height: 1.6; 



     } 



     ul,ol{ 



         padding-left: 20px; 



         list-style-position: inside; 



     } 



 



 



     



     



         



             



         



     我是翻译出来之后，再计算BLEU值的。所以这块不在代码里，附件是BLEU测试的脚本，供参考。周龙



     



     



      



     



  



 



     On 9/12/2019 11:05，wangqi1996<notifications@github.com> wrote： 



 



 



 请问您的代码的哪块是计算BLEU得分的呀

**Comment by wangqi1996** [comment]
感谢~


------------------
祝好！王东琪


 




------------------ 原始邮件 ------------------
发件人: "Long Zhou"<notifications@github.com>;
发送时间: 2019年9月16日(星期一) 晚上10:22
收件人: "wszlong/sb-nmt"<sb-nmt@noreply.github.com>;
抄送: "王东琪"<1528272574@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [wszlong/sb-nmt] BLEU score (#4)



 
 
      
 
 
 
     font{ 
         line-height: 1.6; 
     } 
     ul,ol{ 
         padding-left: 20px; 
         list-style-position: inside; 
     } 
 
 
     
     
         
             
         
     
     
         
             
         
     请查收~
     
         
         
 
         
     
 
     On 9/16/2019 21:07，wangqi1996<notifications@github.com> wrote： 
 
 
 您好，没有收到附件，能帮忙再发一遍嘛？
 
 
 
 感谢
 
 
 
 
 
 
 
 
 
 
 
 ------------------
 
 
 
 祝好！王东琪
 
 
 
 
 
 
 
 
 
 
 
  
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 ------------------ 原始邮件 ------------------
 
 
 
 发件人: "Long Zhou"<notifications@github.com>;
 
 
 
 发送时间: 2019年9月12日(星期四) 下午2:44
 
 
 
 收件人: "wszlong/sb-nmt"<sb-nmt@noreply.github.com>;
 
 
 
 抄送: "王东琪"<1528272574@qq.com>;"Author"<author@noreply.github.com>;
 
 
 
 主题: Re: [wszlong/sb-nmt] BLEU score (#4)
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
  
 
 
 
  
 
 
 
       
 
 
 
  
 
 
 
  
 
 
 
  
 
 
 
      font{ 
 
 
 
          line-height: 1.6; 
 
 
 
      } 
 
 
 
      ul,ol{ 
 
 
 
          padding-left: 20px; 
 
 
 
          list-style-position: inside; 
 
 
 
      } 
 
 
 
  
 
 
 
  
 
 
 
      
 
 
 
      
 
 
 
          
 
 
 
              
 
 
 
          
 
 
 
      我是翻译出来之后，再计算BLEU值的。所以这块不在代码里，附件是BLEU测试的脚本，供参考。周龙
 
 
 
      
 
 
 
      
 
 
 
       
 
 
 
      
 
 
 
   
 
 
 
  
 
 
 
      On 9/12/2019 11:05，wangqi1996<notifications@github.com> wrote： 
 
 
 
  
 
 
 
  
 
 
 
  请问您的代码的哪块是计算BLEU得分的呀

**Comment by wangqi1996** [comment]
冒昧打扰，有没有训练好的模型可以供外部调用的呀？因为之前自己训练两次，结果都不是很好，不知道是自己哪一步做错了。


------------------
祝好！王东琪


 




------------------ 原始邮件 ------------------
发件人: "Long Zhou"<notifications@github.com>;
发送时间: 2019年9月16日(星期一) 晚上10:22
收件人: "wszlong/sb-nmt"<sb-nmt@noreply.github.com>;
抄送: "王东琪"<1528272574@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [wszlong/sb-nmt] BLEU score (#4)



 
 
      
 
 
 
     font{ 
         line-height: 1.6; 
     } 
     ul,ol{ 
         padding-left: 20px; 
         list-style-position: inside; 
     } 
 
 
     
     
         
             
         
     
     
         
             
         
     请查收~
     
         
         
 
         
     
 
     On 9/16/2019 21:07，wangqi1996<notifications@github.com> wrote： 
 
 
 您好，没有收到附件，能帮忙再发一遍嘛？
 
 
 
 感谢
 
 
 
 
 
 
 
 
 
 
 
 ------------------
 
 
 
 祝好！王东琪
 
 
 
 
 
 
 
 
 
 
 
  
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 ------------------ 原始邮件 ------------------
 
 
 
 发件人: "Long Zhou"<notifications@github.com>;
 
 
 
 发送时间: 2019年9月12日(星期四) 下午2:44
 
 
 
 收件人: "wszlong/sb-nmt"<sb-nmt@noreply.github.com>;
 
 
 
 抄送: "王东琪"<1528272574@qq.com>;"Author"<author@noreply.github.com>;
 
 
 
 主题: Re: [wszlong/sb-nmt] BLEU score (#4)
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
  
 
 
 
  
 
 
 
       
 
 
 
  
 
 
 
  
 
 
 
  
 
 
 
      font{ 
 
 
 
          line-height: 1.6; 
 
 
 
      } 
 
 
 
      ul,ol{ 
 
 
 
          padding-left: 20px; 
 
 
 
          list-style-position: inside; 
 
 
 
      } 
 
 
 
  
 
 
 
  
 
 
 
      
 
 
 
      
 
 
 
          
 
 
 
              
 
 
 
          
 
 
 
      我是翻译出来之后，再计算BLEU值的。所以这块不在代码里，附件是BLEU测试的脚本，供参考。周龙
 
 
 
      
 
 
 
      
 
 
 
       
 
 
 
      
 
 
 
   
 
 
 
  
 
 
 
      On 9/12/2019 11:05，wangqi1996<notifications@github.com> wrote： 
 
 
 
  
 
 
 
  
 
 
 
  请问您的代码的哪块是计算BLEU得分的呀
